services:
  - type: web
    name: portfolio-new-client
    env: static
    buildCommand: pnpm run build-client:prod
    staticPublishPath: services/client/dist
    envVars:
      - fromGroup: portfolio-new-env-shared
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: portfolio-new-server
    plan: free
    env: node
    buildCommand: pnpm run build-server:prod
    startCommand: pnpm run start-server:prod
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-new-db
          property: connectionString
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - fromGroup: portfolio-new-env-shared
    buildFilter:
      paths:
        - services/server/**
        - packages/**
        - pnpm-workspace.yaml
        - pnpm-lock.yaml
        - .npmrc
        - render.yaml

databases:
  - name: portfolio-new-db
    plan: free
    postgresMajorVersion: 15
    ipAllowList: []

envVarGroups:
  - name: portfolio-new-env-shared
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ORIGIN
        value: https://portfolio-new-server.onrender.com
      - key: CLIENT_ORIGIN
        value: https://portfolio-new-client.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: HUSKY
        value: 0
      - key: NODE_VERSION
        value: 18.12.1
      - key: SKIP_INSTALL_DEPS
        value: true
        # disable husky install
      - key: CI
        value: true
